stages:          
  - install
  - test
  - lint
  - build
  - deploy


install:      
  stage: install
  script:
    - mkdir npm install

unit-tests:      
  stage: test
  script:
    - mkdir npm run test

lint-test:   
  stage: lint    
  script:
    - mkdir npm run lint

build-android:   
  stage: build    
  script:
    - mkdir cd android
    - mkdir ./gradlew assembleRelease

deploy:      
  stage: deploy
  environment: production
  script:
    - echo "Deploying mocked application..."
    - echo "Application successfully mocked deployed."
