stages:          
  # - install
  - test
  - lint
  - deploy


# install-dependencies-job:      
#   stage: install
#   script:
#     - npm install

unit-tests-job:      
  stage: test
  script:
    - npm run test

lint-test-job:   
  stage: lint    
  script:
    - npm run lint

deploy-job:      
  stage: deploy
  environment: production
  script:
    - echo "Deploying mocked application..."
    - echo "Application successfully mocked deployed."
